= OpenAPI Diff Tool Gradle Plugin

== Introduction
The
https://github.com/OpenAPITools/openapi-diff[OpenAPITools Diff Tool] is useful in comparing 2 OpenAPI specification files. As part of the original repository a maven plugin is included but for those of us that prefer Gradle there was no plugin to be found. This repository contains the code to implement such a plugin.



The plugin has been implemented with an Extension, allowing for the configuration options to be passed in a block assigned with "openapi_diff", and can be used in the build.gradle file

[source,groovy]
----
plugins {
    id 'com.x3t.gradle.plugins.openapi.openapi_diff'
}

openapi_diff {
    originalFile = "old_specification.yaml"
    newFile = "new_specification.yaml"
}
----

The functionality can also be used by creating a task in the build.gradle similar to

.V1.x
[source,groovy]
----
plugins {
    id 'com.x3t.gradle.plugins.openapi.openapi_diff'
}

task triggerCompatible(type: com.x3t.gradle.plugins.openapi.OpenapiDiffPluginTask){
    originalFile = "${projectDir}/old_specification.yaml"
    newFile = "${projectDir}/new_specification.yaml"
}
----

.V2.x
[source,groovy]
----
plugins {
    id 'com.x3t.gradle.plugins.openapi.openapi_diff'
}

task triggerCompatible(type: com.x3t.gradle.plugins.openapi.OpenapiDiffPluginTask){
    originalFile = file("${projectDir}/old_specification.yaml")
    newFile = file("${projectDir}/new_specification.yaml")
}
----

== Options

[%header,cols="1,1,1,1,1,3"]
|===
|Property name
|Type
|Version
|Default Value
|Required
|Description

|originalFile |Property<String> |1.x |*No Default* |Yes |Filename for the original version of the specification.

|newFile |Property<String> |1.x |*No Default* |Yes |Filename for the original version of the specification.

|originalFile |RegularFileProperty |2.x |*No Default* |Yes |File for the original version of the specification.

|newFile |RegularFileProperty |2.x |*No Default* |Yes |File for the original version of the specification.

|failOnChange |Property<Boolean> |1.x,2.x |false |No |Set to true if you wish for the build to fail on any changes.


|failOnIncompatible |Property<Boolean> |1.x,2.x |false |No |Set to true if you wish for the build to fail on incompatible changes.

|htmlReport |Property<Boolean> |1.x,2.x |false |No |Enable to create a comparison report in HTML format.

|jsonReport |Property<Boolean> |1.x,2.x |false |No |Enable to create a comparison report in JSON format.

|textReport |Property<Boolean> |1.x,2.x |false |No |Enable to create a comparison report Plaintext format.

|markdownReport |Property<Boolean> |1.x,2.x |false |No |Enable to create a comparison report Markdown format.

|asciidocReport |Property<Boolean> |1.x,2.x |false |No |Enable to create a comparison report Asciidoc format.

|reportName |Property<String> |1.x,2.x | "build/Openapi_Diff_Report" |No |The location and name to use for any report file.
|===

NOTE: The reportName property is used in the creation of the report files.

If this is left as default then the reports will be named

[rows="1,1,1,1"]
|===
|"build/Openapi_Diff_Report.txt"
|"build/Openapi_Diff_Report.json"
|"build/Openapi_Diff_Report.md"
|"build/Openapi_Diff_Report.html"
|"build/Openapi_Diff_Report.adoc"
|===

depending on which options are enabled.

== Building & Testing

=== Build
To build the plugin you can use the standard Gradle commands of

[source,bash]
----
./gradlew jar
----

To publish to your local maven repository

[source,bash]
----
./gradlew publish
----

If the version is set with "-SNAPSHOT" it will automatically publish locally to a sub-directory called repo.

=== Local Testing

To perform testing local you can run the Gradle build in the demo sub-directory. This will use the ./repo directory to source the plugin for testing.
[NOTE]
====
You must run "./gradlew publish" in the base directory to create the repo sub-directory containing the plugin to be tested.
====

[source,bash]
----
cd demo

../gradlew testTasks             # Expect a build failure due to one of the tasks being configured to fail if the files are different (below)
../gradlew triggerCompatible     # Trigger the build and fail if the 2 files are not compatible OpenAPI versions
../gradlew triggerFailOnChange   # Trigger the build and fail if the files are different

../gradlew testReports           # Will generate the reports in the different formats (below)
../gradlew createAsciidocReport  # Create a report in AsciiDoc format
../gradlew createDifferentReport # Create a report in a text format with a specified name 
../gradlew createHtmlReport      # Create a report in HTML format
../gradlew createJsonReport      # Create a reoprt in JSON format
../gradlew createMarkdownReport  # Create a report in MarkDown format
../gradlew createTextReport      # Create a report in a text format
----

Another way to test the plugin is to run the following from the root directory.

[source,bash]
----
./gradlew test functionalTest
----

This will run JUnit tests and will trigger TestKit tests with the functionalTest task.

== Publish Plugin (For internal use)

To publish the plugin you need to

. Ensure the API key and secret, for x3tadmin, have been added to ~/.gradle/gradle.properties
. The version string has been updated to remove "-SNAPSHOT" and is greater than the last published version.

You then need to open a terminal and run

[source,bash]
----
./gradlew publishPlugins
----

